if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DirichletMultinomial")
library("DirichletMultinomial")
library(DirichletMultinomial)
library(lattice)
library(xtable)
library(parallel)
options(width=70, digits=2)
full <- FALSE
.qualitative <- DirichletMultinomial:::.qualitative
dev.off <- function(...) invisible(grDevices::dev.off(...))
fl <- system.file(package="DirichletMultinomial", "extdata","Twins.csv")
count <- t(as.matrix(read.csv(fl, row.names=1)))
cnts <- log10(colSums(count))
pdf("taxon-counts.pdf")
densityplot(cnts, xlim=range(cnts), xlab="Taxon representation (log 10 count)")
dev.off()
if (full) {fit <- mclapply(1:7, dmn, count=count, verbose=TRUE)
  save(fit, file=file.path(tempdir(), "fit.rda"))  } else data(fit)
fit[[5]]

lplc <- sapply(fit, laplace)
pdf("min-laplace.pdf")
plot(lplc, type="b", xlab="Number of Dirichlet Components", ylab="Model Fit")
dev.off()
(best <- fit[[which.min(lplc)]])
mixturewt(best)
head(mixture(best), 3)

pdf("fitted.pdf")
splom(log(fitted(best)))
dev.off()

p0 <- fitted(fit[[1]], scale=TRUE)
p4 <- fitted(best, scale=TRUE)
colnames(p4) <- paste("m", 1:4, sep="")
(meandiff <- colSums(abs(p4-as.vector(p0))))
sum(meandiff)
diff <- rowSums(abs(p4 - as.vector(p0)))
o <- order(diff, decreasing=TRUE)
cdiff <- cumsum(diff[o]) / sum(diff)
df <- head(cbind(Mean=p0[o], p4[o,], diff=diff[o], cdiff), 10)
pdf("heatmap1.pdf")
heatmapdmn(count, fit[[1]], best, 30)
dev.off()
