figure <- read.delim("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/significant_functions.txt", header = TRUE,check.names=FALSE)

figure$group<-factor(figure$group, levels = c("DOL",
                                              "Subject",
                                              "Diet",
                                              "Antibiotics",
                                              "MEDS",
                                              "Maternal"))

figure$variable<-factor(figure$variable, levels = c("DOL",
                                                    "Acetaminophen_recent",
                                                    "caffeine_recent",
                                                    "CalciumGluconate_recent/acute",
                                                    "Chlorathiazide_recent/acute",
                                                    "Cholecalciferol_recent/acute",
                                                    "Dexamethasone_recent",
                                                    "dopamine_recent",
                                                    "famotidine_recent/acute",
                                                    "fentanyl_recent",
                                                    "Hydrocortisone_recent",
                                                    "Indomethacin_recent",
                                                    "Insulin_recent",
                                                    "Iron_recent",
                                                    "Lasix_recent",
                                                    "Midazolam_recent",
                                                    "Morphine_belong",
                                                    "MV_iron_recent",
                                                    "MV_noIron_recent",
                                                    "Phenobarbitol_recent",
                                                    "PotassiumChloride_recent",
                                                    "SodiumBicarbonate_recent",
                                                    "SodiumChloride_recent",
                                                    "Surfactant_recent",
                                                    "VitaminA_recent/acute",
                                                    "ANTIM_recent",
                                                    "Recent_amingoglycoside",
                                                    "Recent_glycopeptide",
                                                    "Recent_lincosamide",
                                                    "Recent_macrolide",
                                                    "Recent_carbapenem",
                                                    "Recent_4th_gen_cephalosporin",
                                                    "Recent_3rd_gen_cephalosporin",
                                                    "Recent_2nd_gen_cephalosporin",
                                                    "Recent_1st_gen_cephalosporin",
                                                    "Recent_penicillin",
                                                    "formula_cumulative_per",
                                                    "milk_cumulative_per",
                                                    "multiple",
                                                    "route",
                                                    "Sex",
                                                    "Birthweight",
                                                    "GA_birth",
                                                    "mat_chorio",
                                                    "mat_diabetes",
                                                    "mat_preeclampsia",
                                                    "mat_steroids",
                                                    "mat_inpatient_meds",
                                                    "mat_inpt_antimicrobe",
                                                    "mat_outpt_antimicrobial",
                                                    "mat_ppbmi",
                                                    "mat_age",
                                                    "Maternal_race"))

levels(figure$variable) <- c("Day of life",
  "Acetaminophen",
  "Caffeine",
  "Calcium Gluconate",
  "Chlorathiazide",
  "Cholecalciferol",
  "Dexamethasone",
  "Dopamine",
  "Famotidine",
  "Fentanyl",
  "Hydrocortisone",
  "Indomethacin",
  "Insulin",
  "Iron",
  "Lasix",
  "Midazolam",
  "Morphine",
  "Multi-Vitamin/Iron",
  "Multi-Vitamint",
  "Phenobarbitol",
  "Potassium Chloride",
  "Sodium Bicarbonate",
  "Sodium Chloride",
  "Surfactant",
  "Vitamin A",
  "Antimicrobials",
  "Amingoglycoside",
  "Glycopeptide",
  "Lincosamide",
  "Macrolide",
  "Carbapenem",
  "4th Gen Cephalosporin",
  "3rd Gen Cephalosporin",
  "2nd Gen Cephalosporin",
  "1st Gen Cephalosporin",
  "Penicillin",
  "Formula",
  "Milk",
  "Multiple",
  "Route",
  "Sex",
  "Birthweight",
  "Gestational age",
  "Chorio",
  "Diabetes",
  "Preeclampsia",
  "Steroids",
  "Inpatient medication",
  "Inpatient antibiotics",
  "Outpatient antibiotics",
  "BMI",
  "Age",
  "Race")

figure$timeframe<-factor(figure$timeframe, levels = c("10_DOL",
                                              "20_DOL",
                                              "30_DOL",
                                              "40_DOL",
                                              "50_DOL",
                                              "60_DOL"))
levels(figure$timeframe)<-c("1-10","11-20","21-30","31-40","41-50",">50")




#significant plot
sig_plot<-ggplot(figure, aes(fill=significance_variable, y=variable, x=value,alpha=significance_variable)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("#F2F2F2","white","#BFBFBF","#d72631","#79a7d3","#077b8a","#e3b448","#5c3c92","#d2601a"))+
  scale_alpha_manual(values = c(1,0,1,1,1,1,1,1,1))+
  xlab("r-squared")+facet_grid(group~timeframe,scales = "free_y",space = "free_y")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_rect(fill = "transparent",color="grey"),
        plot.background = element_rect(fill = "transparent",color = NA),axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),axis.title.x=element_text(size=14, vjust = 1,face='bold'),
        strip.text.y = element_blank(),
        axis.text.y= element_text(size=10,face='bold',colour='black'),
        axis.text.x= element_text(size=8,face='bold',colour='black'),panel.spacing = unit(0.75, "lines"),strip.text.x = element_text(size=12,face='bold',colour='black'))+
  scale_x_continuous(limits=c(0,0.125),breaks=c(0,0.06,0.12))
sig_plot
ggsave("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/sig_test.png", sig_plot, width=8, height=10, bg = "transparent")


###non-significant plot

figure <- read.delim("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/non_significant.txt", header = TRUE,check.names=FALSE)

figure$group<-factor(figure$group, levels = c("DOL",
                                              "Subject",
                                              "Diet",
                                              "Antibiotics",
                                              "MEDS",
                                              "Maternal"))

figure$variable<-factor(figure$variable, levels = c("DOL",
                                                    "Acetaminophen_recent",
                                                    "caffeine_recent",
                                                    "CalciumGluconate_recent/acute",
                                                    "Chlorathiazide_recent/acute",
                                                    "Cholecalciferol_recent/acute",
                                                    "Dexamethasone_recent",
                                                    "dopamine_recent",
                                                    "famotidine_recent/acute",
                                                    "fentanyl_recent",
                                                    "Hydrocortisone_recent",
                                                    "Indomethacin_recent",
                                                    "Insulin_recent",
                                                    "Iron_recent",
                                                    "Lasix_recent",
                                                    "Midazolam_recent",
                                                    "Morphine_belong",
                                                    "MV_iron_recent",
                                                    "MV_noIron_recent",
                                                    "Phenobarbitol_recent",
                                                    "PotassiumChloride_recent",
                                                    "SodiumBicarbonate_recent",
                                                    "SodiumChloride_recent",
                                                    "Surfactant_recent",
                                                    "VitaminA_recent/acute",
                                                    "ANTIM_recent",
                                                    "Recent_amingoglycoside",
                                                    "Recent_glycopeptide",
                                                    "Recent_lincosamide",
                                                    "Recent_macrolide",
                                                    "Recent_carbapenem",
                                                    "Recent_4th_gen_cephalosporin",
                                                    "Recent_3rd_gen_cephalosporin",
                                                    "Recent_2nd_gen_cephalosporin",
                                                    "Recent_1st_gen_cephalosporin",
                                                    "Recent_penicillin",
                                                    "formula_cumulative_per",
                                                    "milk_cumulative_per",
                                                    "multiple",
                                                    "route",
                                                    "Sex",
                                                    "Birthweight",
                                                    "GA_birth",
                                                    "mat_chorio",
                                                    "mat_diabetes",
                                                    "mat_preeclampsia",
                                                    "mat_steroids",
                                                    "mat_inpatient_meds",
                                                    "mat_inpt_antimicrobe",
                                                    "mat_outpt_antimicrobial",
                                                    "mat_ppbmi",
                                                    "mat_age",
                                                    "Maternal_race"))

levels(figure$variable) <- c("Day of life",
                             "Acetaminophen",
                             "Caffeine",
                             "Calcium Gluconate",
                             "Chlorathiazide",
                             "Cholecalciferol",
                             "Dexamethasone",
                             "Dopamine",
                             "Famotidine",
                             "Fentanyl",
                             "Hydrocortisone",
                             "Indomethacin",
                             "Insulin",
                             "Iron",
                             "Lasix",
                             "Midazolam",
                             "Morphine",
                             "Multi-Vitamin/Iron",
                             "Multi-Vitamint",
                             "Phenobarbitol",
                             "Potassium Chloride",
                             "Sodium Bicarbonate",
                             "Sodium Chloride",
                             "Surfactant",
                             "Vitamin A",
                             "Antimicrobials",
                             "Amingoglycoside",
                             "Glycopeptide",
                             "Lincosamide",
                             "Macrolide",
                             "Carbapenem",
                             "4th Gen Cephalosporin",
                             "3rd Gen Cephalosporin",
                             "2nd Gen Cephalosporin",
                             "1st Gen Cephalosporin",
                             "Penicillin",
                             "Formula",
                             "Milk",
                             "Multiple",
                             "Route",
                             "Sex",
                             "Birthweight",
                             "Gestational age",
                             "Chorio",
                             "Diabetes",
                             "Preeclampsia",
                             "Steroids",
                             "Inpatient medication",
                             "Inpatient antibiotics",
                             "Outpatient antibiotics",
                             "BMI",
                             "Age",
                             "Race")

figure$timeframe<-factor(figure$timeframe, levels = c("10_DOL",
                                                      "20_DOL",
                                                      "30_DOL",
                                                      "40_DOL",
                                                      "50_DOL",
                                                      "60_DOL"))
levels(figure$timeframe)<-c("1-10","11-20","21-30","31-40","41-50",">50")

#non-significant plot
ns_plot<-ggplot(figure, aes(fill=significance, y=variable, x=value,alpha=significance)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("#F2F2F2","white","#BFBFBF","#404040"))+
  scale_alpha_manual(values = c(0, 0, 1,1))+
  xlab("")+facet_grid(group~timeframe,scales = "free_y",space = "free_y")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_rect(fill = "transparent",color="grey"),
        axis.title.y=element_blank(),axis.title.x=element_text(size=14, vjust = 1,face='bold',colour='white'),axis.ticks = element_blank(),
        panel.border = element_blank(),strip.text.y = element_blank(),axis.ticks.y=element_blank(),
        axis.text.y= element_text(size=10,face='bold',colour='white'),
        axis.text.x= element_text(size=6,face='bold',colour='white'),panel.spacing = unit(0.75, "lines"),strip.text.x = element_text(size=12,face='bold',colour='black'))+
  scale_x_continuous(limits=c(0,0.125),breaks=c(0,0.04,0.08,0.12))
ns_plot
ggsave("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/non_sig_test.png", ns_plot, width=8, height=10, bg = "transparent")

###########################
#######associations########
###########################
associations <- read.delim("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/associations_functions.txt", header = TRUE,check.names=FALSE)

associations$group<-factor(associations$group, levels = c("DOL",
                                              "Subject",
                                              "Diet",
                                              "Antibiotics",
                                              "MEDS",
                                              "Maternal"))

associations$variable<-factor(associations$variable, levels = c("DOL",
                                                    "Acetaminophen_recent",
                                                    "caffeine_recent",
                                                    "CalciumGluconate_recent/acute",
                                                    "Chlorathiazide_recent/acute",
                                                    "Cholecalciferol_recent/acute",
                                                    "Dexamethasone_recent",
                                                    "dopamine_recent",
                                                    "famotidine_recent/acute",
                                                    "fentanyl_recent",
                                                    "Hydrocortisone_recent",
                                                    "Indomethacin_recent",
                                                    "Insulin_recent",
                                                    "Iron_recent",
                                                    "Lasix_recent",
                                                    "Midazolam_recent",
                                                    "Morphine_belong",
                                                    "MV_iron_recent",
                                                    "MV_noIron_recent",
                                                    "Phenobarbitol_recent",
                                                    "PotassiumChloride_recent",
                                                    "SodiumBicarbonate_recent",
                                                    "SodiumChloride_recent",
                                                    "Surfactant_recent",
                                                    "VitaminA_recent/acute",
                                                    "ANTIM_recent",
                                                    "Recent_amingoglycoside",
                                                    "Recent_glycopeptide",
                                                    "Recent_lincosamide",
                                                    "Recent_macrolide",
                                                    "Recent_carbapenem",
                                                    "Recent_4th_gen_cephalosporin",
                                                    "Recent_3rd_gen_cephalosporin",
                                                    "Recent_2nd_gen_cephalosporin",
                                                    "Recent_1st_gen_cephalosporin",
                                                    "Recent_penicillin",
                                                    "formula_cumulative_per",
                                                    "milk_cumulative_per",
                                                    "multiple",
                                                    "route",
                                                    "Sex",
                                                    "Birthweight",
                                                    "GA_birth",
                                                    "mat_chorio",
                                                    "mat_diabetes",
                                                    "mat_preeclampsia",
                                                    "mat_steroids",
                                                    "mat_inpatient_meds",
                                                    "mat_inpt_antimicrobe",
                                                    "mat_outpt_antimicrobial",
                                                    "mat_ppbmi",
                                                    "mat_age",
                                                    "Maternal_race"))

levels(associations$variable) <- c("Day of life",
                             "Acetaminophen",
                             "Caffeine",
                             "Calcium Gluconate",
                             "Chlorathiazide",
                             "Cholecalciferol",
                             "Dexamethasone",
                             "Dopamine",
                             "Famotidine",
                             "Fentanyl",
                             "Hydrocortisone",
                             "Indomethacin",
                             "Insulin",
                             "Iron",
                             "Lasix",
                             "Midazolam",
                             "Morphine",
                             "Multi-Vitamin/Iron",
                             "Multi-Vitamint",
                             "Phenobarbitol",
                             "Potassium Chloride",
                             "Sodium Bicarbonate",
                             "Sodium Chloride",
                             "Surfactant",
                             "Vitamin A",
                             "Antimicrobials",
                             "Amingoglycoside",
                             "Glycopeptide",
                             "Lincosamide",
                             "Macrolide",
                             "Carbapenem",
                             "4th Gen Cephalosporin",
                             "3rd Gen Cephalosporin",
                             "2nd Gen Cephalosporin",
                             "1st Gen Cephalosporin",
                             "Penicillin",
                             "Formula",
                             "Milk",
                             "Multiple",
                             "Route",
                             "Sex",
                             "Birthweight",
                             "Gestational age",
                             "Chorio",
                             "Diabetes",
                             "Preeclampsia",
                             "Steroids",
                             "Inpatient medication",
                             "Inpatient antibiotics",
                             "Outpatient antibiotics",
                             "BMI",
                             "Age",
                             "Race")

figure$timeframe<-factor(figure$timeframe, levels = c("10_DOL",
                                                      "20_DOL",
                                                      "30_DOL",
                                                      "40_DOL",
                                                      "50_DOL",
                                                      "60_DOL"))
levels(figure$timeframe)<-c("1-10","11-20","21-30","31-40","41-50",">50")

associations_funcs<-ggplot(associations, aes(y=variable, x=proportion)) + 
  geom_bar(position="stack", stat="identity",fill="#f3ca20",color="black") +
  xlab("Associations")+facet_grid(group~.,scales = "free_y",space = "free_y")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_rect(fill = "transparent",color=NA),
        plot.background = element_rect(fill = "transparent",color = NA),axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),axis.title.x=element_text(size=14, vjust = 1,face='bold'),
        strip.text.y = element_blank(),
        axis.text.y= element_text(size=10,face='bold',colour='black'),
        axis.text.x= element_text(size=8,face='bold',colour='black'),panel.spacing = unit(0.75, "lines"))+
  scale_x_continuous(limits=c(0,100),breaks=c(0,25,50,75,100))
associations_funcs
ggsave("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/assocaitions_functions.png", associations_funcs, width=3, height=10, bg = "transparent")




############
####Taxa####
############
figure <- read.delim("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/significant_taxa.txt", header = TRUE,check.names=FALSE)

figure$group<-factor(figure$group, levels = c("DOL",
                                              "Subject",
                                              "Diet",
                                              "Antibiotics",
                                              "MEDS",
                                              "Maternal"))

figure$variable<-factor(figure$variable, levels = c("DOL",
                                                    "Acetaminophen_recent",
                                                    "caffeine_recent",
                                                    "CalciumGluconate_recent/acute",
                                                    "Chlorathiazide_recent/acute",
                                                    "Cholecalciferol_recent/acute",
                                                    "Dexamethasone_recent",
                                                    "dopamine_recent",
                                                    "famotidine_recent/acute",
                                                    "fentanyl_recent",
                                                    "Hydrocortisone_recent",
                                                    "Indomethacin_recent",
                                                    "Insulin_recent",
                                                    "Iron_recent",
                                                    "Lasix_recent",
                                                    "Midazolam_recent",
                                                    "Morphine_belong",
                                                    "MV_iron_recent",
                                                    "MV_noIron_recent",
                                                    "Phenobarbitol_recent",
                                                    "PotassiumChloride_recent",
                                                    "SodiumBicarbonate_recent",
                                                    "SodiumChloride_recent",
                                                    "Surfactant_recent",
                                                    "VitaminA_recent/acute",
                                                    "ANTIM_recent",
                                                    "Recent_amingoglycoside",
                                                    "Recent_glycopeptide",
                                                    "Recent_lincosamide",
                                                    "Recent_macrolide",
                                                    "Recent_carbapenem",
                                                    "Recent_4th_gen_cephalosporin",
                                                    "Recent_3rd_gen_cephalosporin",
                                                    "Recent_2nd_gen_cephalosporin",
                                                    "Recent_1st_gen_cephalosporin",
                                                    "Recent_penicillin",
                                                    "formula_cumulative_per",
                                                    "milk_cumulative_per",
                                                    "multiple",
                                                    "route",
                                                    "Sex",
                                                    "Birthweight",
                                                    "GA_birth",
                                                    "mat_chorio",
                                                    "mat_diabetes",
                                                    "mat_preeclampsia",
                                                    "mat_steroids",
                                                    "mat_inpatient_meds",
                                                    "mat_inpt_antimicrobe",
                                                    "mat_outpt_antimicrobial",
                                                    "mat_ppbmi",
                                                    "mat_age",
                                                    "Maternal_race"))

levels(figure$variable) <- c("Day of life",
                             "Acetaminophen",
                             "Caffeine",
                             "Calcium Gluconate",
                             "Chlorathiazide",
                             "Cholecalciferol",
                             "Dexamethasone",
                             "Dopamine",
                             "Famotidine",
                             "Fentanyl",
                             "Hydrocortisone",
                             "Indomethacin",
                             "Insulin",
                             "Iron",
                             "Lasix",
                             "Midazolam",
                             "Morphine",
                             "Multi-Vitamin/Iron",
                             "Multi-Vitamint",
                             "Phenobarbitol",
                             "Potassium Chloride",
                             "Sodium Bicarbonate",
                             "Sodium Chloride",
                             "Surfactant",
                             "Vitamin A",
                             "Antimicrobials",
                             "Amingoglycoside",
                             "Glycopeptide",
                             "Lincosamide",
                             "Macrolide",
                             "Carbapenem",
                             "4th Gen Cephalosporin",
                             "3rd Gen Cephalosporin",
                             "2nd Gen Cephalosporin",
                             "1st Gen Cephalosporin",
                             "Penicillin",
                             "Formula",
                             "Milk",
                             "Multiple",
                             "Route",
                             "Sex",
                             "Birthweight",
                             "Gestational age",
                             "Chorio",
                             "Diabetes",
                             "Preeclampsia",
                             "Steroids",
                             "Inpatient medication",
                             "Inpatient antibiotics",
                             "Outpatient antibiotics",
                             "BMI",
                             "Age",
                             "Race")

figure$timeframe<-factor(figure$timeframe, levels = c("10_DOL",
                                                      "20_DOL",
                                                      "30_DOL",
                                                      "40_DOL",
                                                      "50_DOL",
                                                      "60_DOL"))
levels(figure$timeframe)<-c("1-10","11-20","21-30","31-40","41-50",">50")




#significant plot
sig_plot<-ggplot(figure, aes(fill=significance_variable, y=variable, x=value,alpha=significance_variable)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("#F2F2F2","white","#BFBFBF","#d72631","#79a7d3","#077b8a","#e3b448","#5c3c92","#d2601a"))+
  scale_alpha_manual(values = c(1,0,1,1,1,1,1,1,1))+
  xlab("r-squared")+facet_grid(group~timeframe,scales = "free_y",space = "free_y")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_rect(fill = "transparent",color="grey"),
        plot.background = element_rect(fill = "transparent",color = NA),axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),axis.title.x=element_text(size=14, vjust = 1,face='bold'),
        strip.text.y = element_blank(),
        axis.text.y= element_text(size=10,face='bold',colour='black'),
        axis.text.x= element_text(size=8,face='bold',colour='black'),panel.spacing = unit(0.75, "lines"),strip.text.x = element_text(size=12,face='bold',colour='black'))+
  scale_x_continuous(limits=c(0,0.085),breaks=c(0,0.04,0.08))
sig_plot
ggsave("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/sig_taxa.png", sig_plot, width=8, height=10, bg = "transparent")


###non-significant plot

figure <- read.delim("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/non_significant_taxa.txt", header = TRUE,check.names=FALSE)

figure$group<-factor(figure$group, levels = c("DOL",
                                              "Subject",
                                              "Diet",
                                              "Antibiotics",
                                              "MEDS",
                                              "Maternal"))

figure$variable<-factor(figure$variable, levels = c("DOL",
                                                    "Acetaminophen_recent",
                                                    "caffeine_recent",
                                                    "CalciumGluconate_recent/acute",
                                                    "Chlorathiazide_recent/acute",
                                                    "Cholecalciferol_recent/acute",
                                                    "Dexamethasone_recent",
                                                    "dopamine_recent",
                                                    "famotidine_recent/acute",
                                                    "fentanyl_recent",
                                                    "Hydrocortisone_recent",
                                                    "Indomethacin_recent",
                                                    "Insulin_recent",
                                                    "Iron_recent",
                                                    "Lasix_recent",
                                                    "Midazolam_recent",
                                                    "Morphine_belong",
                                                    "MV_iron_recent",
                                                    "MV_noIron_recent",
                                                    "Phenobarbitol_recent",
                                                    "PotassiumChloride_recent",
                                                    "SodiumBicarbonate_recent",
                                                    "SodiumChloride_recent",
                                                    "Surfactant_recent",
                                                    "VitaminA_recent/acute",
                                                    "ANTIM_recent",
                                                    "Recent_amingoglycoside",
                                                    "Recent_glycopeptide",
                                                    "Recent_lincosamide",
                                                    "Recent_macrolide",
                                                    "Recent_carbapenem",
                                                    "Recent_4th_gen_cephalosporin",
                                                    "Recent_3rd_gen_cephalosporin",
                                                    "Recent_2nd_gen_cephalosporin",
                                                    "Recent_1st_gen_cephalosporin",
                                                    "Recent_penicillin",
                                                    "formula_cumulative_per",
                                                    "milk_cumulative_per",
                                                    "multiple",
                                                    "route",
                                                    "Sex",
                                                    "Birthweight",
                                                    "GA_birth",
                                                    "mat_chorio",
                                                    "mat_diabetes",
                                                    "mat_preeclampsia",
                                                    "mat_steroids",
                                                    "mat_inpatient_meds",
                                                    "mat_inpt_antimicrobe",
                                                    "mat_outpt_antimicrobial",
                                                    "mat_ppbmi",
                                                    "mat_age",
                                                    "Maternal_race"))

levels(figure$variable) <- c("Day of life",
                             "Acetaminophen",
                             "Caffeine",
                             "Calcium Gluconate",
                             "Chlorathiazide",
                             "Cholecalciferol",
                             "Dexamethasone",
                             "Dopamine",
                             "Famotidine",
                             "Fentanyl",
                             "Hydrocortisone",
                             "Indomethacin",
                             "Insulin",
                             "Iron",
                             "Lasix",
                             "Midazolam",
                             "Morphine",
                             "Multi-Vitamin/Iron",
                             "Multi-Vitamint",
                             "Phenobarbitol",
                             "Potassium Chloride",
                             "Sodium Bicarbonate",
                             "Sodium Chloride",
                             "Surfactant",
                             "Vitamin A",
                             "Antimicrobials",
                             "Amingoglycoside",
                             "Glycopeptide",
                             "Lincosamide",
                             "Macrolide",
                             "Carbapenem",
                             "4th Gen Cephalosporin",
                             "3rd Gen Cephalosporin",
                             "2nd Gen Cephalosporin",
                             "1st Gen Cephalosporin",
                             "Penicillin",
                             "Formula",
                             "Milk",
                             "Multiple",
                             "Route",
                             "Sex",
                             "Birthweight",
                             "Gestational age",
                             "Chorio",
                             "Diabetes",
                             "Preeclampsia",
                             "Steroids",
                             "Inpatient medication",
                             "Inpatient antibiotics",
                             "Outpatient antibiotics",
                             "BMI",
                             "Age",
                             "Race")

figure$timeframe<-factor(figure$timeframe, levels = c("10_DOL",
                                                      "20_DOL",
                                                      "30_DOL",
                                                      "40_DOL",
                                                      "50_DOL",
                                                      "60_DOL"))
levels(figure$timeframe)<-c("1-10","11-20","21-30","31-40","41-50",">50")

#non-significant plot
ns_plot<-ggplot(figure, aes(fill=significance, y=variable, x=value,alpha=significance)) + 
  geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("#F2F2F2","white","#BFBFBF","#404040"))+
  scale_alpha_manual(values = c(0, 0, 1,1))+
  xlab("")+facet_grid(group~timeframe,scales = "free_y",space = "free_y")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_rect(fill = "transparent",color="grey"),
        axis.title.y=element_blank(),axis.title.x=element_text(size=14, vjust = 1,face='bold',colour='white'),axis.ticks = element_blank(),
        panel.border = element_blank(),strip.text.y = element_blank(),axis.ticks.y=element_blank(),
        axis.text.y= element_text(size=10,face='bold',colour='white'),
        axis.text.x= element_text(size=6,face='bold',colour='white'),panel.spacing = unit(0.75, "lines"),strip.text.x = element_text(size=12,face='bold',colour='black'))+
  scale_x_continuous(limits=c(0,0.085),breaks=c(0,0.04,0.08))
ns_plot
ggsave("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/non_sig_taxa.png", ns_plot, width=8, height=10, bg = "transparent")


###########################
#######associations########
###########################
associations <- read.delim("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/associations_taxa.txt", header = TRUE,check.names=FALSE)

associations$group<-factor(associations$group, levels = c("DOL",
                                                          "Subject",
                                                          "Diet",
                                                          "Antibiotics",
                                                          "MEDS",
                                                          "Maternal"))

associations$variable<-factor(associations$variable, levels = c("DOL",
                                                                "Acetaminophen_recent",
                                                                "caffeine_recent",
                                                                "CalciumGluconate_recent/acute",
                                                                "Chlorathiazide_recent/acute",
                                                                "Cholecalciferol_recent/acute",
                                                                "Dexamethasone_recent",
                                                                "dopamine_recent",
                                                                "famotidine_recent/acute",
                                                                "fentanyl_recent",
                                                                "Hydrocortisone_recent",
                                                                "Indomethacin_recent",
                                                                "Insulin_recent",
                                                                "Iron_recent",
                                                                "Lasix_recent",
                                                                "Midazolam_recent",
                                                                "Morphine_belong",
                                                                "MV_iron_recent",
                                                                "MV_noIron_recent",
                                                                "Phenobarbitol_recent",
                                                                "PotassiumChloride_recent",
                                                                "SodiumBicarbonate_recent",
                                                                "SodiumChloride_recent",
                                                                "Surfactant_recent",
                                                                "VitaminA_recent/acute",
                                                                "ANTIM_recent",
                                                                "Recent_amingoglycoside",
                                                                "Recent_glycopeptide",
                                                                "Recent_lincosamide",
                                                                "Recent_macrolide",
                                                                "Recent_carbapenem",
                                                                "Recent_4th_gen_cephalosporin",
                                                                "Recent_3rd_gen_cephalosporin",
                                                                "Recent_2nd_gen_cephalosporin",
                                                                "Recent_1st_gen_cephalosporin",
                                                                "Recent_penicillin",
                                                                "formula_cumulative_per",
                                                                "milk_cumulative_per",
                                                                "multiple",
                                                                "route",
                                                                "Sex",
                                                                "Birthweight",
                                                                "GA_birth",
                                                                "mat_chorio",
                                                                "mat_diabetes",
                                                                "mat_preeclampsia",
                                                                "mat_steroids",
                                                                "mat_inpatient_meds",
                                                                "mat_inpt_antimicrobe",
                                                                "mat_outpt_antimicrobial",
                                                                "mat_ppbmi",
                                                                "mat_age",
                                                                "Maternal_race"))

levels(associations$variable) <- c("Day of life",
                                   "Acetaminophen",
                                   "Caffeine",
                                   "Calcium Gluconate",
                                   "Chlorathiazide",
                                   "Cholecalciferol",
                                   "Dexamethasone",
                                   "Dopamine",
                                   "Famotidine",
                                   "Fentanyl",
                                   "Hydrocortisone",
                                   "Indomethacin",
                                   "Insulin",
                                   "Iron",
                                   "Lasix",
                                   "Midazolam",
                                   "Morphine",
                                   "Multi-Vitamin/Iron",
                                   "Multi-Vitamint",
                                   "Phenobarbitol",
                                   "Potassium Chloride",
                                   "Sodium Bicarbonate",
                                   "Sodium Chloride",
                                   "Surfactant",
                                   "Vitamin A",
                                   "Antimicrobials",
                                   "Amingoglycoside",
                                   "Glycopeptide",
                                   "Lincosamide",
                                   "Macrolide",
                                   "Carbapenem",
                                   "4th Gen Cephalosporin",
                                   "3rd Gen Cephalosporin",
                                   "2nd Gen Cephalosporin",
                                   "1st Gen Cephalosporin",
                                   "Penicillin",
                                   "Formula",
                                   "Milk",
                                   "Multiple",
                                   "Route",
                                   "Sex",
                                   "Birthweight",
                                   "Gestational age",
                                   "Chorio",
                                   "Diabetes",
                                   "Preeclampsia",
                                   "Steroids",
                                   "Inpatient medication",
                                   "Inpatient antibiotics",
                                   "Outpatient antibiotics",
                                   "BMI",
                                   "Age",
                                   "Race")

associations_funcs<-ggplot(associations, aes(y=variable, x=proportion)) + 
  geom_bar(position="stack", stat="identity",fill="#f3ca20",color="black") +
  xlab("Associations")+facet_grid(group~.,scales = "free_y",space = "free_y")+
  theme(legend.position = "none",
        panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.background = element_rect(fill = "transparent",color=NA),
        plot.background = element_rect(fill = "transparent",color = NA),axis.ticks.y=element_blank(),
        axis.title.y=element_blank(),axis.title.x=element_text(size=14, vjust = 1,face='bold'),
        strip.text.y = element_blank(),
        axis.text.y= element_text(size=10,face='bold',colour='black'),
        axis.text.x= element_text(size=8,face='bold',colour='black'),panel.spacing = unit(0.75, "lines"))+
  scale_x_continuous(limits=c(0,100),breaks=c(0,25,50,75,100))
associations_funcs
ggsave("./Desktop/Projects/NEC/final_analysis/control_analysis/DNA_PERMANOVA/Figure/assocaitions_taxa.png", associations_funcs, width=3, height=10, bg = "transparent")

#test for distribution of associations over time 
#taxa
input_mxn_table = structure(list(D_10 = c(12L, 28L), D_20 = c(7L, 39L), D_30 = c(13L, 34L), D_40 = c(9L, 37L), D_50 = c(3L, 37L), D60 = c(7L, 36L)), class = "data.frame", row.names = c("Outcome", "No-Outcome")) 
input_mxn_table 
fisher.test(input_mxn_table)

#functions
input_mxn_table = structure(list(D_10 = c(15L, 25L), D_20 = c(6L, 40L), D_30 = c(12L, 35L), D_40 = c(9L, 37L), D_50 = c(2L, 38L), D60 = c(7L, 36L)), class = "data.frame", row.names = c("Outcome", "No-Outcome")) 
input_mxn_table 
fisher.test(input_mxn_table)

